name: CD services/common-ml

on:
  workflow_run:
    workflows: CI services/common-ml
    branches: main
    types: completed
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  deploy-common-ml:
    uses:
      ./.github/workflows/service-deploy.yml
    with:
      working-directory: services/common-ml
      project-flag: common-ml
    secrets: inherit