name: CD fastapi ml

on:
  workflow_run:
    workflows: CI services/fastapi-ml
    branches: main
    types: completed
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  deploy-fastapi-ml:
    uses:
      ./.github/workflows/service-deploy.yml
    with:
      working-directory: services/fastapi-ml
      project-flag: fastapi-ml
    secrets: inherit