---
name: CI libs/mq

on:
  pull_request:
    paths:
      - '.github/workflows/lib-test.yml'
      - '.github/workflows/ci-lib-mq.yml'
      - 'libs/mq/**'
  push:
    branches:
      - main
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-lib-mq:
    uses:
      ./.github/workflows/lib-test.yml
    with:
      working-directory: libs/mq
      requirement-file: libs/mq/poetry.lock
      project-flag: mq
    secrets: inherit
      