---
name: CI libs/ml

on:
  pull_request:
    paths:
      - '.github/workflows/lib-test.yml'
      - '.github/workflows/ci-lib-ml.yml'
      - 'libs/ml/**'
  push:
    branches:
      - main
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-lib-ml:
    uses:
      ./.github/workflows/lib-test.yml
    with:
      working-directory: libs/ml
      requirement-file: libs/ml/poetry.lock
      project-flag: ml
    secrets: inherit
      