---
name: CI libs/telemetry

on:
  pull_request:
    paths:
      - '.github/workflows/lib-test.yml'
      - '.github/workflows/ci-lib-telemetry.yml'
      - 'libs/telemetry/**'
  push:
    branches:
      - main
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-lib-telemetry:
    uses:
      ./.github/workflows/lib-test.yml
    with:
      working-directory: libs/telemetry
      requirement-file: libs/telemetry/poetry.lock
      project-flag: telemetry
    secrets: inherit
      